### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by srl295** [tvdias/github-tagger#16]
```
Run tvdias/github-tagger@2949d204e2f571a709c2af13a90759460fb56595
6
internal/modules/cjs/loader.js:800
7
    throw err;
8
    ^
9

10
Error: Cannot find module '@actions/core'
11
Require stack:
12
- /home/runner/work/_actions/tvdias/github-tagger/2949d204e2f571a709c2af13a90759460fb56595/lib/main.js
13
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
14
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
15
    at Module.require (internal/modules/cjs/loader.js:852:19)
16
    at require (internal/modules/cjs/helpers.js:74:18)
17
    at Object.<anonymous> (/home/runner/work/_actions/tvdias/github-tagger/2949d204e2f571a709c2af13a90759460fb56595/lib/main.js:19:27)
18
    at Module._compile (internal/modules/cjs/loader.js:959:30)
19
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
20
    at Module.load (internal/modules/cjs/loader.js:815:32)
21
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
22
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
23
  code: 'MODULE_NOT_FOUND',
24
  requireStack: [
25
    '/home/runner/work/_actions/tvdias/github-tagger/2949d204e2f571a709c2af13a90759460fb56595/lib/main.js'
26
  ]
27
}
```

**Comment by pxpm** [comment]
I've created a package with this one as a base. 

I am not a Javascript developer but I use this package to scratch my own hitch. If you need it too, here it is: https://github.com/pxpm/github-tag-action
